spring:
  application:
    name: data-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/RefuelingWuhan?characterEncoding=utf8
server:
  port: 9001
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://admin:123456@e-1:8761/eureka/,http://admin:123456@e-2:8762/eureka/
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
